Snapshot candidate: ERD-27, ERD-69, ERD-70, ERD-71, ERD-76
ndsev/erdblick pull request #90
Opened 2024-02-09 08:04 UTC by Waguramu

**Goal**: prepare a snapshot release candidate.

**Scope**:
[ERD-27](https://youtrack.nds-association.org/issue/ERD-27)Toggle for Cesium OSM Layer
[ERD-69](https://youtrack.nds-association.org/issue/ERD-69)Encode camera layer state in URL
[ERD-70](https://youtrack.nds-association.org/issue/ERD-70)Responsive layout
[ERD-71](https://youtrack.nds-association.org/issue/ERD-71)Improve map layer selection panel
[ERD-76](https://youtrack.nds-association.org/issue/ERD-76)Basic support of multiple styles
* Erdblick components and services refactoring

**Deliverables**:
* Refactored app component.
* Map panel component.
* Style service.

**How to test**:
1. Build and run as usual.

OR

1. Test via mapviewer build as usual.

**Notes**:
* ensure that config.json and config/styles/* directories are present to test for multiple styles
* styles config expects the following structure:
```json
{
   "styles": [
       { "name": "style name", "url": "style url" }, ...
   ]
}
```

2024-02-11 22:59 UTC, MisterGC commented
I started to review this combined PR - some initial remarks based on the screenshot below 
- Tested with Firefox on Ubuntu 22.04 using a 4k Monitor
- [ ] Fix the text position and size in the search field
- [ ] No focus indicator needed for the Show/Hide and focus buttons
- [ ] As you can see there is no initial style loaded by default, is this intended?
- [ ] I suggest to remove the headline ('Maps Layers')
- [ ] What about renaming 'Maps' to 'Maps & Layers'?
- [ ] The OSM ImageryProvider is also a layer, therefore I'd put it inside Maps & Layers too - later this could be a drop down that allows to select any of the supported (or a custom) ImageryProvider
![image](https://github.com/ndsev/erdblick/assets/2118573/60334249-5ecd-4bf5-b50f-a7a0fc3fd23f)

2024-02-12 15:53 UTC, MisterGC commented
- [ ] Replace this section of the README with a description about how it works now and how I can preconfigure multiple styles:

<img width="1012" alt="image" src="https://github.com/ndsev/erdblick/assets/2118573/cf4e654e-524d-4d09-8de2-d970d99988a7">

2024-02-13 19:30 UTC, MisterGC commented
Although we can keep it for the upcoming snapshot - I'd say we definitely should work on the general layout - have a look how far away search'n'settings and inspection from each other (Firefox, 4k Monitor, 100% Zoom)
 
![image](https://github.com/ndsev/erdblick/assets/2118573/e8120f15-73e8-422b-9773-4f4ce6a23cc9)

2024-02-13 21:12 UTC, MisterGC commented
Some more suggestions for improvements: 
- [ ] Instead of the visibility icon and a on/off slider we should just use one icon which clearly indicate activated/deactivated for both OSM and mapget provided map feature layer
- [ ] Fix the the too dense layout, give it a little more air - at least the scrollbar overlap and the tile level selection clipping and the non- clearly visible separation between OSM and the other layer are clear issues

To keep in mind for the future: 
- we'll add support for transparancy for any layer, think about how this could be easily covered without the need to totally break the GUI
- [ ] 
- [ ] 

![image](https://github.com/ndsev/erdblick/assets/2118573/dff99d35-5456-4d1b-86d8-a266d99fea64)

2024-02-16 08:49 UTC, MisterGC commented
- [ ] After re-using the URL in the browser I need to change MapViewer viewport before I see any content
- [ ] Deactivation of Layers has no effect (toggling the 'eye' button)

2024-02-19 19:39 UTC, Waguramu commented
- [ ]  Make sure that the styles get reloaded from file on reload.
- [ ]  Deactivate the default style when there are more styles available.
- [ ]  Add a possibility to merge external configs into the existing config when run in Docker?

2024-02-20 11:37 UTC, MisterGC commented
- [ ] I can now expand/collapse nodes in the inspection panel by clicking on the row, but this prevents me from copying the values of cells, if I mark text, the row expands/collapses and the text gets unmarked - user should be able to do both copy and collapse/expand by clicking on the row
- [ ] URL encoded camera viewport should use WGS84 coords (not global 3d coords!?)

2024-02-27 21:35 UTC, Waguramu commented
- [] Fix style toggled state on reload (always active but not applied yet?)

2024-02-28 07:42 UTC, Waguramu commented
WON'T FIX:
- Allow jumpto target selection of targets via keyboard (substantial effort -> create an issue)
- consider filter the list instead of greying out (will lead to confusion and more Angular lifecycle triggers)

2024-03-05 07:13 UTC, josephbirkner requested changes
Took a good long look, found a few things to take care of.

2024-03-05 07:13 UTC, josephbirkner commented on README.md
>  > **Note ⚠️:** While the mature product envisions a rich UI with the ability
This note can be removed, right?

2024-03-05 07:13 UTC, josephbirkner commented on README.md
>  Each rule within the YAML `rules` array can have the following fields. Any field marked with __`*`__ is optional:
The new style options for dashed/arrow lines need to be documented here :)

2024-03-05 07:13 UTC, josephbirkner commented on angular.json
> +                                "glob": "**/*.json",
There was a mention that YAML files are picked up atomatically (In the README).

2024-03-05 07:13 UTC, josephbirkner commented on erdblick_app/app/app.component.ts
Nice cleanup 👍

2024-03-05 07:13 UTC, josephbirkner commented on erdblick_app/app/erdblick.model.ts
> +        console.log("CALLED PROCESS TILE STREAM")
These console logs should be removed.

2024-03-05 07:13 UTC, josephbirkner commented on erdblick_app/app/erdblick.model.ts
> +    loadStyles() {
Why is this not in the StyleService?

2024-03-05 07:13 UTC, josephbirkner commented on erdblick_app/app/erdblick.model.ts
> +    cycleImportedStyle(styleId: string, remove= false) {
Style service migration?

2024-03-05 07:13 UTC, josephbirkner commented on erdblick_app/app/erdblick.model.ts
> +        this.styles = null;
Since we have a StyleService, I would prefer if these members are there, and any style access goes through the service.

2024-03-05 07:13 UTC, josephbirkner commented on erdblick_app/app/erdblick.model.ts
> +                this.styles?.forEach((style, styleId) => {
These two blocks should be unified into `for(let style of styleService.allStyles()){...}`, where allStyles yields from styles and importedStyles.

2024-03-05 07:13 UTC, josephbirkner commented on erdblick_app/app/erdblick.model.ts
> +        // Re-render all present batches with the new style.
Delete this block of commented-out code

2024-03-05 07:13 UTC, josephbirkner commented on erdblick_app/app/map.service.ts
> +// export interface ErdblickMap {
TBR

2024-03-05 07:13 UTC, josephbirkner commented on erdblick_app/app/erdblick.view.ts
> +            this.viewer.camera.position
imo this line does nothing

2024-03-05 07:13 UTC, josephbirkner commented on erdblick_app/app/map.service.ts
>  export class MapService {
I see that you are struggling with the lifecycle of the ErdblickModel class. But why not just fix that lifecycle? (Turn the model into a service?) MapService is a great candidate for becoming a soup of random utility functions. I'd say, let's think of a way to get rid of it.

2024-03-05 07:13 UTC, josephbirkner commented on erdblick_app/app/style.service.ts
> +export class StyleService {
Please add a docstring to specify the purpose of the style service. Currently, there is a lot of mixed responsibility regarding style management between this class and the ErdblickModel.

2024-03-05 07:13 UTC, josephbirkner commented on libs/core/include/erdblick/cesium-interface/primitive.h
> +     * See https://cesium.com/learn/cesiumjs/ref-doc/PolylineColorAppearance.html
Docstring/Link are wrong (here and below)

2024-03-05 07:13 UTC, josephbirkner commented on libs/core/include/erdblick/rule.h
> +    std::string materialColor_ = "#ffffff";
Why have materialColor separate from color? Just use the existing color member.

2024-03-05 07:13 UTC, josephbirkner commented on libs/core/include/erdblick/visualization.h
> +    CesiumPrimitive* getPrimitiveForDashMaterial(const FeatureStyleRule &rule);
Docstrings for these two functions are missing.

2024-03-05 07:13 UTC, josephbirkner commented on libs/core/include/erdblick/rule.h
> +    std::string gapColor_ = "#ffffff";
Please store the gapColor as glm::fvec4.

2024-03-05 07:13 UTC, josephbirkner commented on libs/core/include/erdblick/cesium-interface/cesium.h
> +    CesiumClass Polyline;
I think none of the added classes here are needed, right?

2024-03-05 07:13 UTC, josephbirkner commented on libs/core/src/visualization.cpp
> +    for (size_t i = isOddSize ? midpointIndex : midpointIndex - 1; i > 0; i--) {
```suggestion
    for (size_t i = isOddSize ? midpointIndex : midpointIndex - 1; i >= 0; i--) {
```

2024-03-05 07:13 UTC, josephbirkner commented on libs/core/src/visualization.cpp
> +    for (size_t i = isOddSize ? midpointIndex + 1 : midpointIndex; i < points.size(); i++) {
The iteration starting point for both of these loops should be the same index, and it should't matter whether the point count is odd or even.

2024-03-05 14:31 UTC, MisterGC commented
Feedback regarding style configuration:

**Must-Haves**
- [ ] Default style cannot be refreshed - make it refreshable
- [ ] The erdblick docs talk about automatically picked up yaml-files and the example config does not use the `yaml` extension for the url part, but it is needed
     e.g. `my-style.yaml` needs an entry with the extension: `"url": "my-style.yaml"` - change the docs that the file + ext has to be provided
- [ ] Having a broken style, leads to a white screen the corresponding style id is shown in the UI, the console gives no explicit information that what went wrong
     in the scope of the parsing - at least show the yaml parsing error in the console, later we will intro a proper error reporting
- [ ] Providing a non-valid style URL still shows the style with the id, but the MapViewer is broken, console inspection is needed to understand there is an error
     - considering the docs are fixed, I'd say the style config should just not show up if the URL is invalid or even better show the style with `<style-id> (ERR: see browser console)`

**Nice-To-Have**
- [ ] If the `config.yaml` is broken the MapViewer falls back to using the default style only, which is good, but the user doesn't know if he has entered a wrong
     style config
- [ ] Disabling and Enabling style seems to make the style the top-level one, so depending on the order of enabling/disabling different styles may be on top
- [ ] Why is importing a style a two-click action, `+Import`, `Choose File`, `Confirm Import` - imo it would be no problem to import the style directly after selecting it

2024-03-06 08:31 UTC, Waguramu commented on erdblick_app/app/erdblick.model.ts
> +    loadStyles() {
Needs to be addressed separately

2024-03-06 08:31 UTC, Waguramu commented on erdblick_app/app/erdblick.model.ts
> +    cycleImportedStyle(styleId: string, remove= false) {
Needs to be addressed separately

2024-03-06 08:31 UTC, Waguramu commented on erdblick_app/app/erdblick.model.ts
> +        this.styles = null;
Needs to be addressed separately

2024-03-06 08:31 UTC, Waguramu commented on erdblick_app/app/erdblick.model.ts
> +                this.styles?.forEach((style, styleId) => {
Needs to be addressed separately

2024-03-06 08:31 UTC, Waguramu commented on erdblick_app/app/map.service.ts
>  export class MapService {
Needs to be addressed separately

2024-03-06 08:32 UTC, Waguramu commented on angular.json
> +                                "glob": "**/*.json",
They are?

2024-03-06 11:30 UTC, josephbirkner approved these changes
Ok, I think we can merge this now :)

Here is my list of refactoring needs:

* Find a way to ensure that coreLib loading happens before anything else, and that coreLib access is hassle-free from everywhere, probably using an Angular Resolver (https://chat.openai.com/share/e/981edbfc-01c3-4fa8-b121-f519bf7b18ba).
* Migrate style parsing from `ErdblickModel` to `StyleService`.
* Merge ErdblickStyle/ErdblickStyleData/StyleService.styles/StyleService.importedStyles.
* Merge Model and MapService.
* Migrate URL parameter handling from AppComponent to ParameterService.
* Turn ErdblickView into a real component or service?
* visualization is currently a `.component.ts`, but that is misleading.

2024-03-06 12:00 UTC, merged